In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
# Read data
path = "../Raw/IMF_CPIS_WIDEF.csv"
df_cpis = pd.read_csv(path)
df_cpis

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,Annual,ABW,Aruba,IMF_CPIS_I_A_D_L_O_BP6,"Assets, Debt Securities, Denominated in Other ...",USD,US dollars,IMF_CNT_COUNTRY_1,Counterpart: World,...,NaN,NaN,NaN,445700000.0,464700000.0,540300000.0,567400000.0,5.860948e+08,NaN,NaN
1,A,Annual,ABW,Aruba,IMF_CPIS_I_A_D_L_SN_BP6,"Assets, Debt Securities, Short or Negative Pos...",USD,US dollars,IMF_CNT_COUNTRY_1,Counterpart: World,...,NaN,NaN,NaN,0.0,-27500000.0,-14700000.0,-41300000.0,2.877000e+07,-5.327087e+06,-1.583689e+07
2,A,Annual,ABW,Aruba,IMF_CPIS_I_A_D_L_SN_BP6,"Assets, Debt Securities, Short or Negative Pos...",USD,US dollars,IMF_CNT_COUNTRY_112,Counterpart: United Kingdom,...,NaN,NaN,NaN,NaN,NaN,NaN,-1300000.0,NaN,NaN,NaN
3,A,Annual,ABW,Aruba,IMF_CPIS_I_A_D_L_SN_BP6,"Assets, Debt Securities, Short or Negative Pos...",USD,US dollars,IMF_CNT_COUNTRY_134,Counterpart: Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.120000e+06,NaN,NaN
4,A,Annual,ABW,Aruba,IMF_CPIS_I_A_D_L_SN_BP6,"Assets, Debt Securities, Short or Negative Pos...",USD,US dollars,IMF_CNT_COUNTRY_142,Counterpart: Norway,...,NaN,NaN,NaN,NaN,NaN,NaN,-5500000.0,3.950000e+06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464507,A,Annual,ZWE,Zimbabwe,IMF_CPIS_I_L_T_T_T_BP6_DV,"Liabilities, Total Investment, Derived",USD,US dollars,IMF_CNT_COUNTRY_961,"Counterpart: Slovenia, Rep. of",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00
1464508,A,Annual,ZWE,Zimbabwe,IMF_CPIS_I_L_T_T_T_BP6_DV,"Liabilities, Total Investment, Derived",USD,US dollars,IMF_CNT_COUNTRY_962,"Counterpart: North Macedonia, Republic of",...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00
1464509,A,Annual,ZWE,Zimbabwe,IMF_CPIS_I_L_T_T_T_BP6_DV,"Liabilities, Total Investment, Derived",USD,US dollars,IMF_CNT_COUNTRY_964,"Counterpart: Poland, Rep. of",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00
1464510,A,Annual,ZWE,Zimbabwe,IMF_CPIS_I_L_T_T_T_BP6_DV,"Liabilities, Total Investment, Derived",USD,US dollars,IMF_CNT_COUNTRY_967,"Counterpart: Kosovo, Rep. of",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00
1464511,A,Annual,ZWE,Zimbabwe,IMF_CPIS_I_L_T_T_T_BP6_DV,"Liabilities, Total Investment, Derived",USD,US dollars,IMF_CNT_COUNTRY_968,Counterpart: Romania,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
indicators_to_keep = [
    "Assets, Total Investment",
    "Assets, Equity",
    "Assets, Debt Securities",
]

df_cpis = df_cpis[df_cpis["INDICATOR_LABEL"].isin(indicators_to_keep)]

In [17]:
# Remove comp_3
df_cpis = df_cpis[df_cpis["COMP_BREAKDOWN_3_LABEL"] == "Sector: All sectors"].copy()

In [18]:
df_cpis["INDICATOR_LABEL"].value_counts()

INDICATOR_LABEL
Assets, Debt Securities     215269
Assets, Total Investment     77273
Assets, Equity               71302
Name: count, dtype: int64

In [19]:
# only numeric and 4 digits
year_cols = [col for col in df_cpis.columns if col.isdigit() and len(col) == 4]

df_cpis_long = df_cpis.melt(
    id_vars=["REF_AREA", "REF_AREA_LABEL", "INDICATOR", "INDICATOR_LABEL",
             "COMP_BREAKDOWN_1", "COMP_BREAKDOWN_1_LABEL",
             "COMP_BREAKDOWN_2", "COMP_BREAKDOWN_2_LABEL",
             "COMP_BREAKDOWN_3", "COMP_BREAKDOWN_3_LABEL",
             "UNIT_MEASURE", "UNIT_MEASURE_LABEL"],
    value_vars=year_cols,
    var_name="year",
    value_name="value"
)

df_cpis_long["year"] = df_cpis_long["year"].astype(int)
df_cpis_long = df_cpis_long.dropna(subset=["value"]).reset_index(drop=True)

df_cpis_long

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,year,value
0,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_1,Counterpart: World,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,1.805003e+10
1,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_111,Counterpart: United States,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,3.558190e+09
2,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_112,Counterpart: United Kingdom,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,1.285639e+06
3,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_113,Counterpart: Guernsey,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,0.000000e+00
4,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_117,Counterpart: Jersey,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484765,ZAF,South Africa,IMF_CPIS_I_A_T_T_T_BP6,"Assets, Total Investment",IMF_CNT_COUNTRY_960,"Counterpart: Croatia, Rep. of",IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,2023,0.000000e+00
3484766,ZAF,South Africa,IMF_CPIS_I_A_T_T_T_BP6,"Assets, Total Investment",IMF_CNT_COUNTRY_961,"Counterpart: Slovenia, Rep. of",IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,2023,1.079846e+05
3484767,ZAF,South Africa,IMF_CPIS_I_A_T_T_T_BP6,"Assets, Total Investment",IMF_CNT_COUNTRY_964,"Counterpart: Poland, Rep. of",IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,2023,6.425084e+06
3484768,ZAF,South Africa,IMF_CPIS_I_A_T_T_T_BP6,"Assets, Total Investment",IMF_CNT_COUNTRY_968,Counterpart: Romania,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,2023,0.000000e+00
3484769,ZAF,South Africa,IMF_CPIS_I_A_T_T_T_BP6,"Assets, Total Investment",IMF_CNT_COUNTRY_983,Counterpart: Not Specified (including Confiden...,IMF_CNT_SEC_T,Counterpart Sector: Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,2023,3.596427e+08

In [20]:
df_cpis_long["COMP_BREAKDOWN_1_LABEL"].value_counts()

COMP_BREAKDOWN_1_LABEL
Counterpart: World                                           21739
Counterpart: United States                                   19383
Counterpart: United Kingdom                                  18875
Counterpart: Netherlands, The                                18514
Counterpart: France                                          18210
                                                             ...
Counterpart: South Sudan, Rep. of                            11556
Counterpart: Kosovo, Rep. of                                 11213
Counterpart: International Organizations                      6365
Counterpart: World Minus 25 Significant Financial Centers     3608
Counterpart: Netherlands Antilles                             2021
Name: count, Length: 246, dtype: int64

In [21]:
df_cpis_long["COMP_BREAKDOWN_2_LABEL"].value_counts()

COMP_BREAKDOWN_2_LABEL
Counterpart Sector: Total Holdings                                                            1266812
Counterpart Sector: Nonfinancial Corporations, Households and NPISHs                           234109
Counterpart Sector: Financial Corporations                                                     230988
Counterpart Sector: Deposit Taking Corporations                                                227664
Counterpart Sector: Depository-taking Corporations except the Central Bank                     227622
Counterpart Sector: Other Financial Corporations                                               227318
Counterpart Sector: General Government                                                         225076
Counterpart Sector: Other Financial Corporations: Other                                        221870
Counterpart Sector: Other Financial Corporations: Insurance Corporations and Pension Funds     213485
Counterpart Sector: Central Bank                                                               206815
Counterpart Sector: Other Financial Corporations: Money Market Funds                           203011
Name: count, dtype: int64

In [22]:
df_cpis_long["COMP_BREAKDOWN_3_LABEL"].value_counts()

COMP_BREAKDOWN_3_LABEL
Sector: All sectors    3484770
Name: count, dtype: int64

In [28]:
df_cpis_long["UNIT_MEASURE_LABEL"].value_counts()

UNIT_MEASURE_LABEL
US dollars    3484770
Name: count, dtype: int64

In [25]:
# Remove the "Counterpart:" in the COMP_BREAKDOWN_1_LABEL
df_cpis_long["COMP_BREAKDOWN_1_LABEL"] = df_cpis_long["COMP_BREAKDOWN_1_LABEL"].str.replace("Counterpart:", "", regex=False).str.strip()
# Remove the "Counterpart Sector:" in the COMP_BREAKDOWN_2_LABEL
df_cpis_long["COMP_BREAKDOWN_2_LABEL"] = df_cpis_long["COMP_BREAKDOWN_2_LABEL"].str.replace("Counterpart Sector:", "", regex=False).str.strip()
df_cpis_long.head()

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,year,value
0,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_1,World,IMF_CNT_SEC_T,Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,1.805003e+10
1,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_111,United States,IMF_CNT_SEC_T,Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,3.558190e+09
2,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_112,United Kingdom,IMF_CNT_SEC_T,Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,1.285639e+06
3,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_113,Guernsey,IMF_CNT_SEC_T,Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,0.000000e+00
4,ARG,Argentina,IMF_CPIS_I_A_D_L_T_BP6,"Assets, Debt Securities",IMF_CNT_COUNTRY_117,Jersey,IMF_CNT_SEC_T,Total Holdings,IMF_SEC_T,Sector: All sectors,USD,US dollars,1997,0.000000e+00

In [27]:
# Find if comp 1 or 2 has any : in them now? Will show if we have missed classifications
display(df_cpis_long["COMP_BREAKDOWN_1_LABEL"].value_counts())
display(df_cpis_long["COMP_BREAKDOWN_2_LABEL"].value_counts())

COMP_BREAKDOWN_1_LABEL
World                                           21739
United States                                   19383
United Kingdom                                  18875
Netherlands, The                                18514
France                                          18210
                                                ...
South Sudan, Rep. of                            11556
Kosovo, Rep. of                                 11213
International Organizations                      6365
World Minus 25 Significant Financial Centers     3608
Netherlands Antilles                             2021
Name: count, Length: 246, dtype: int64

COMP_BREAKDOWN_2_LABEL
Total Holdings                                                            1266812
Nonfinancial Corporations, Households and NPISHs                           234109
Financial Corporations                                                     230988
Deposit Taking Corporations                                                227664
Depository-taking Corporations except the Central Bank                     227622
Other Financial Corporations                                               227318
General Government                                                         225076
Other Financial Corporations: Other                                        221870
Other Financial Corporations: Insurance Corporations and Pension Funds     213485
Central Bank                                                               206815
Other Financial Corporations: Money Market Funds                           203011
Name: count, dtype: int64

In [29]:
# Save to cleaned data
savepath = "../Clean/IMF_CPIS.csv"
df_cpis_long.to_csv(savepath, index=False)