In [67]:
#%pip install forex-python fredapi --quiet

In [68]:
import pandas as pd
import numpy as np

In [69]:
# # get the .env file with the api keys
# from dotenv import load_dotenv
# import os

# load_dotenv()  # Loads .env file

# fred_api_key = os.getenv("FRED_API_KEY")

In [70]:
filepath = "../Raw/pwt110.xlsx"
df = pd.read_excel(filepath, sheet_name="Data")
df

,countrycode,country,currency_unit,year,rgdpe,rgdpo,pop,emp,avh,hc,...,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k
0,ABW,Aruba,Aruban Guilder,1950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,Aruban Guilder,1951,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,Aruban Guilder,1952,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,Aruban Guilder,1953,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,Aruban Guilder,1954,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13685,ZWE,Zimbabwe,US Dollar,2019,46541.140625,45106.468750,15.271368,5.272343,1903.71,2.713408,...,0.189066,-0.242234,0.038880,0.501244,0.534841,0.345942,0.505318,0.441230,0.339268,1.346716
13686,ZWE,Zimbabwe,US Dollar,2020,45985.085938,45983.898438,15.526888,5.206007,1889.45,2.746586,...,0.110438,-0.165574,0.029654,0.500685,0.519637,0.290690,0.772591,0.680202,0.324105,1.353769
13687,ZWE,Zimbabwe,US Dollar,2021,45625.347656,44440.199219,15.797210,5.298346,2011.57,2.770661,...,0.172298,-0.279770,0.024442,0.616105,0.549380,0.301370,0.558099,0.497615,0.347739,1.064607
13688,ZWE,Zimbabwe,US Dollar,2022,50148.527344,48054.238281,16.069056,5.344455,2172.04,2.795292,...,0.220504,-0.391468,0.021712,0.660731,0.478931,0.280778,0.487665,0.432867,0.301817,1.006796
13689,ZWE,Zimbabwe,US Dollar,2023,52258.898438,50540.847656,16.340822,5.504774,2311.02,2.820498,...,0.179567,-0.308382,0.015704,0.736836,0.507688,0.307323,0.505070,0.474047,0.308811,1.030187

In [71]:
keepcols = ["rgdpna", "rnna", "emp", "pop", "labsh", "delta", "rtfpna"] + ["countrycode", "year"]
df = df[keepcols]
df

,rgdpna,rnna,emp,pop,labsh,delta,rtfpna,countrycode,year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1950
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1951
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1952
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1953
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1954
...,...,...,...,...,...,...,...,...,...
13685,44445.031250,107682.148438,5.272343,15.271368,0.533381,0.059923,1.057740,ZWE,2019
13686,40970.785156,109248.289062,5.206007,15.526888,0.533381,0.060208,0.973187,ZWE,2020
13687,44440.199219,110979.773438,5.298346,15.797210,0.533381,0.060136,1.000000,ZWE,2021
13688,47147.550781,114134.882812,5.344455,16.069056,0.533381,0.059788,0.997026,ZWE,2022
13689,49685.757812,118669.257812,5.504774,16.340822,0.533381,0.061346,0.973139,ZWE,2023

In [72]:
# Rename columns
df = df.rename(columns={
    "rgdpna": "Real GDP",
    "rnna": "Capital Stock",
    "emp": "Worker Population",
    "pop": "Total Population",
    "labsh": "Labour Share",
    "delta": "Depreciation Rate",
    "rtfpna": "TFP",
    # "countrycode": "iso3"
})
df

,Real GDP,Capital Stock,Worker Population,Total Population,Labour Share,Depreciation Rate,TFP,countrycode,year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1950
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1951
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1952
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1953
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1954
...,...,...,...,...,...,...,...,...,...
13685,44445.031250,107682.148438,5.272343,15.271368,0.533381,0.059923,1.057740,ZWE,2019
13686,40970.785156,109248.289062,5.206007,15.526888,0.533381,0.060208,0.973187,ZWE,2020
13687,44440.199219,110979.773438,5.298346,15.797210,0.533381,0.060136,1.000000,ZWE,2021
13688,47147.550781,114134.882812,5.344455,16.069056,0.533381,0.059788,0.997026,ZWE,2022
13689,49685.757812,118669.257812,5.504774,16.340822,0.533381,0.061346,0.973139,ZWE,2023

In [73]:
# # load the mapping
# fx_map = pd.read_csv("../Raw/fx-codes/country_code_to_currency_code.csv")
# # Get intersection with iso3 against country_Code
# iso3_set = set(df["iso3"].dropna().unique())
# fx_cnt_code = set(fx_map["country_Code"].unique())
# intersection = set(iso3_set.intersection(fx_cnt_code))
# print(f"Number of intsersection countries: {len(intersection)}")
# print(f"Number of countries in PWT: {len(iso3_set)}")
# print(f"Number of countries in FX map: {len(fx_cnt_code)}")

# # Join to df to add the currency code
# fx_map["iso3"] = fx_map["country_Code"]
# fx_map["currency_code"] = fx_map["Currency_Code"]

# df = df.merge(fx_map[["iso3", "currency_code"]], on="iso3", how="left")
# df

In [74]:
# import yfinance as yf
# from tqdm import tqdm

# currency_codes = df["currency_code"].dropna().unique()
# # Make the symbols for historical data
# pairs = [f"{c}USD=X" for c in currency_codes if c != "USD" and len(str(c))==3]
# fx_data = yf.download(pairs, start="1990-01-01", end="2026-03-01")["Close"]
# # revert bsck to iso3 codes
# fx_data.columns = [col.split("USD=X")[0] for col in fx_data.columns]
# # group by year and get average
# fx_data.index = pd.to_datetime(fx_data.index)
# fx_data["year"] = fx_data.index.year
# fx_data = fx_data.groupby("year").mean().reset_index()
# # unpivot to long format from columns
# fx_data = fx_data.melt(id_vars=["year"], var_name="currency_code", value_name="fx_usd_avg_close")
# fx_data

In [75]:
# # Join this to df
# df = df.merge(fx_data, left_on=["currency_code", "year"], right_on=["currency_code", "year"], how="left")
# df

In [77]:
df

,Real GDP,Capital Stock,Worker Population,Total Population,Labour Share,Depreciation Rate,TFP,countrycode,year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1950
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1951
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1952
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1953
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABW,1954
...,...,...,...,...,...,...,...,...,...
13685,44445.031250,107682.148438,5.272343,15.271368,0.533381,0.059923,1.057740,ZWE,2019
13686,40970.785156,109248.289062,5.206007,15.526888,0.533381,0.060208,0.973187,ZWE,2020
13687,44440.199219,110979.773438,5.298346,15.797210,0.533381,0.060136,1.000000,ZWE,2021
13688,47147.550781,114134.882812,5.344455,16.069056,0.533381,0.059788,0.997026,ZWE,2022
13689,49685.757812,118669.257812,5.504774,16.340822,0.533381,0.061346,0.973139,ZWE,2023

In [76]:
savepath = "../Clean/pwt.csv"
df.to_csv(savepath, index=False)